/* Public macro histories. No requests, persistence, external libraries or personal inputs. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),D=JSON.parse($('macro-data').textContent),K=JSON.parse($('macro-calendar-data').textContent),H=JSON.parse($('macro-calendar-report').textContent),M=$('macro');
const meta={ust10:['米国債10年金利','%','日次','https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView'],cpi:['CPI / 消費者物価','1982-84=100','月次 / 季節調整なし','https://data.bls.gov/timeseries/CUUR0000SA0'],pce:['PCE / 個人消費物価','2017=100','月次 / 季節調整済み','https://www.bea.gov/data/personal-consumption-expenditures-price-index'],unemployment:['米国失業率','%','月次 / 季節調整済み','https://data.bls.gov/timeseries/LNS14000000'],vix:['VIX / 予想変動率','points','権利確認待ち','https://www.cboe.com/tradable-products/vix/vix-historical-data/'],usdjpy:['USD/JPY / ドル円','JPY / USD','日次 / Fed H.10','https://www.federalreserve.gov/releases/h10/hist/dat00_ja.htm'],wti:['WTI / 原油現物','USD / barrel','日次 / EIA現物','https://www.eia.gov/dnav/pet/hist/RWTCD.htm']};
const family={cpi:'CPI発表',pce:'PCE発表',jobs:'雇用統計',fomc:'FOMC会合最終日'},related={cpi:'cpi',pce:'pce',jobs:'unemployment',fomc:'ust10'};
const calendarSource={cpi:'https://www.bls.gov/schedule/news_release/cpi.htm',jobs:'https://www.bls.gov/schedule/news_release/empsit.htm',pce:'https://www.bea.gov/news/schedule',fomc:'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm'};
const calendarExpected={cpi:12,jobs:12,pce:12,fomc:8};
const healthMeta={live_complete:['公式日程 完全取得','年内必要件数を公式ソースから完全取得。','ok'],live_reviewed_coverage:['公式取得＋レビュー済み範囲','現在年の既存レビュー範囲を公式候補で継続確認。','ok'],partial_rejected:['部分日程を保留','年間日程が未完了のため公開拡張を拒否。','warn'],source_access_blocked:['取得経路ブロック','公式ソースへの取得が403/429等で遮断。レビュー済み値を保持。','warn'],retained_reviewed:['レビュー済み固定値','ライブ更新せず、確認済み日程を保持。','muted'],awaiting_official_schedule:['公式日程待ち','完全な年間公式日程の公開待ち。部分日程は掲載しません。','pending']};
const Q={years:5,series:'all',mode:'yoy',event:null,calendar:'upcoming'};
const epoch=d=>Date.parse(d+'T00:00:00Z'),fmt=(n,d=2)=>new Intl.NumberFormat('ja-JP',{maximumFractionDigits:d,minimumFractionDigits:d}).format(n);
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function append(p,...es){es.forEach(e=>p.append(e));return p;}
function button(text,fn){const b=node('button',text);b.type='button';b.addEventListener('click',fn);return b;}
function link(url,label){const a=node('a',label);a.href=url;a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';return a;}
function yoy(rows){const m=new Map(rows);return rows.flatMap(([d,v])=>{const old=m.get(String(+d.slice(0,4)-1)+d.slice(4));return old===undefined||old===0?[]:[[d,(v/old-1)*100]];});}
function values(s){return Q.mode==='yoy'&&['cpi','pce'].includes(s.id)?yoy(s.observations):s.observations;}
function windowDates(){if(Q.event){const t=epoch(Q.event.date);return [t-100*86400000,t+60*86400000];}const end=epoch(D.attempted_at.slice(0,10)),d=new Date(end);d.setUTCFullYear(d.getUTCFullYear()-Q.years);return [Q.years===0?epoch('2015-01-01'):d.getTime(),end];}
function unit(s){return Q.mode==='yoy'&&['cpi','pce'].includes(s.id)?'% / 前年同月比':meta[s.id][1];}
M.replaceChildren();append(M,node('div','MACRO HISTORY / PRIMARY SOURCES','p-eyebrow'),node('h2','マクロ7系列と経済カレンダー'),node('p','一次データを同じ期間で確認。実データ6系列 / VIXは再掲載条件確認待ち。','p-lead'));
const notice=node('div',undefined,'p-caution');append(notice,node('p','静的配信・リアルタイムではありません。物価・失業率の横軸は統計対象月、カレンダーは発表日です。'),node('p','最新改定値を含みます。過去の発表時点で知り得た値とは限らず、因果関係や売買シグナルを示しません。','small'));M.append(notice);
const controls=node('div',undefined,'macro-controls');for(const [y,l] of [[1,'1年'],[5,'5年'],[10,'10年'],[0,'全期間']]){const b=button(l,()=>{Q.years=y;Q.event=null;render();});b.dataset.macroYears=y;controls.append(b);}for(const [v,l] of [['yoy','物価: 前年比'],['level','物価: 指数水準']]){const b=button(l,()=>{Q.mode=v;render();});b.dataset.macroMode=v;controls.append(b);}M.append(controls);
const selected=node('p','', 'small');selected.id='macro-selection';selected.setAttribute('aria-live','polite');M.append(selected);
const selector=node('div',undefined,'macro-controls');for(const [id,label] of [['all','全系列'],...Object.entries(meta).map(([id,m])=>[id,m[0]])]){const b=button(label,()=>{Q.series=id;render();});b.dataset.macroSeries=id;selector.append(b);}M.append(selector);
const health=node('article',undefined,'p-card calendar-health');health.id='calendar-source-health';append(health,node('h3','Calendar Source Health / 年別カバレッジ'),node('p','BLS・BEA・Federal Reserveを定期確認。完全な年間日程だけ翌年へ拡張し、部分日程や取得障害は状態として明示します。','small'));const healthGrid=node('div',undefined,'calendar-health-grid');health.append(healthGrid);M.append(health);
const eventDetail=node('article',undefined,'p-card');eventDetail.id='macro-event-detail';M.append(eventDetail);
const grid=node('div',undefined,'macro-grid');M.append(grid);const cards=new Map();
for(const s of D.series){const m=meta[s.id],card=node('article',undefined,'p-card macro-card');card.dataset.macroCard=s.id;const value=node('strong','', 'macro-value'),status=node('span','', 'p-badge'),summary=node('p','', 'small'),readout=node('p','', 'small');readout.setAttribute('aria-live','polite');const canvas=node('canvas');canvas.id='macro-chart-'+s.id;canvas.tabIndex=0;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',m[0]+' / '+m[1]);const details=node('details'),table=node('table',undefined,'data-table');append(details,node('summary','元データ / 表示範囲の最新24点'),append(node('div',undefined,'table-wrap'),table));append(card,node('h3',m[0]),status,value,summary,canvas,readout,details,link(m[3],s.id==='vix'?'Cboe / 公式ページ':'一次データ / 出典'));grid.append(card);cards.set(s.id,{card,value,status,summary,canvas,readout,table,details,rows:[],cursor:0});
 const show=i=>{const o=cards.get(s.id),r=o.rows[Math.max(0,Math.min(o.rows.length-1,i))];if(r){o.cursor=Math.max(0,Math.min(o.rows.length-1,i));o.readout.textContent=r[0]+' | '+fmt(r[1])+' '+unit(s);}};
 canvas.addEventListener('pointermove',e=>{const o=cards.get(s.id);if(!o.rows.length)return;const [a,b]=windowDates(),t=a+(e.offsetX-52)/(canvas.clientWidth-70)*(b-a);let best=0;for(let i=1;i<o.rows.length;i++)if(Math.abs(epoch(o.rows[i][0])-t)<Math.abs(epoch(o.rows[best][0])-t))best=i;show(best);});
 canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const o=cards.get(s.id);show(e.key==='Home'?0:e.key==='End'?o.rows.length-1:o.cursor+(e.key==='ArrowRight'?1:-1));});}
function calendarStatus(fam,year){const direct=H.family_year_status?.[fam]?.[String(year)];if(direct&&healthMeta[direct])return direct;const n=K.events.filter(e=>e.family===fam&&e.date.startsWith(String(year)+'-')).length;return n?'retained_reviewed':'awaiting_official_schedule';}
function renderHealth(){healthGrid.replaceChildren();const baseYear=Number(K.checked_at.slice(0,4)),years=[baseYear,baseYear+1];for(const fam of ['cpi','jobs','pce','fomc'])for(const year of years){const status=calendarStatus(fam,year),m=healthMeta[status],n=K.events.filter(e=>e.family===fam&&e.date.startsWith(String(year)+'-')).length,card=node('section',undefined,'calendar-health-item calendar-health-'+m[2]);card.dataset.calendarHealth=fam+'-'+year;card.dataset.calendarStatus=status;append(card,node('h4',year+' / '+family[fam]),node('span',m[0],'p-badge'),node('strong',n+' / '+calendarExpected[fam]+'件','calendar-health-count'),node('p',m[1],'small'),link(calendarSource[fam],'公式日程'));healthGrid.append(card);}const mode=H.mode==='family_merge'?'公式取得＋family completeness gate':'レビュー済みスナップショット';health.append(node('p','判定基準日: '+(H.cutoff_jst||K.checked_at)+' / '+mode+' / 将来公開上限は基準年+1','small calendar-health-note'));}
const calendar=node('article',undefined,'p-card macro-calendar');calendar.id='macro-calendar';const calendarMode=H.mode==='family_merge'?'公式日程を定期確認・完全性ゲート適用':'レビュー済み日程を使用';append(calendar,node('h3','経済カレンダー（公表日）'),node('p','日本時間・夏時間対応 / 日程確認 '+K.checked_at+' / '+calendarMode,'small'));const calControls=node('div',undefined,'macro-controls');for(const [id,label] of [['upcoming','今後の予定'],['all','登録した全日程']]){const b=button(label,()=>{Q.calendar=id;renderCalendar();});b.dataset.macroCalendar=id;calControls.append(b);}const calRows=node('div');append(calendar,calControls,calRows);M.append(calendar);
if(Date.now()-epoch(K.checked_at)>35*86400000)calendar.prepend(node('p','日程の確認から35日超。公式情報で再確認が必要です。','p-caution'));
const revisions=node('details');append(revisions,node('summary','改定検知と制約'),node('p','初回取得前の改定履歴は復元しません。以後の前回取得値との差分を最大50件保持。補助系列の改定と初回発表値の全履歴は対象外です。','small'));for(const r of D.revisions)revisions.append(node('p',r.series+' '+r.date+' '+fmt(r.old)+' -> '+fmt(r.new)+' / '+r.detected_at,'small'));M.append(revisions);
function renderCalendar(){calRows.replaceChildren();const now=new Date().toISOString().slice(0,10),items=K.events.filter(e=>Q.calendar==='all'||e.date>=now);if(!items.length)calRows.append(node('p','該当日程なし。Source Healthで公式日程待ち・取得障害を確認してください。'));
 for(const e of items){const row=node('div',undefined,'macro-event-row');const b=button(family[e.family],()=>{Q.event=e;Q.series='all';activate($('tab-macro'));render();$('macro-event-detail').scrollIntoView({block:'start',behavior:'auto'});});b.dataset.macroEvent=e.id;append(row,node('span',e.time_jst?e.time_jst+' JST':e.date+' ET / 時刻未確認'),b,node('small',e.period?'対象月 '+e.period:'会合日程'),link(e.source,'公式日程'));calRows.append(row);}
 calControls.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(Q.calendar===b.dataset.macroCalendar)));}
function eventInfo(){eventDetail.replaceChildren();eventDetail.hidden=!Q.event;if(!Q.event)return;const e=Q.event;append(eventDetail,node('h3',e.date+' / '+family[e.family]),node('p',(e.time_jst?e.time_jst+' JST':'時刻は確認が必要')+' / 予想値: 未収録 / サプライズ計算なし','small'));
 const stat=D.series.find(s=>s.id===related[e.family]);if(e.period&&stat){const r=values(stat).find(r=>r[0]===e.period+'-01');append(eventDetail,node('p','対象月の現収録値: '+(r?fmt(r[1])+' '+unit(stat):'未収録')+' / 初回発表値とは限りません。'));}
 for(const id of ['ust10','usdjpy','wti']){const s=D.series.find(s=>s.id===id),before=s.observations.filter(r=>r[0]<e.date).at(-1),after=s.observations.find(r=>r[0]>=e.date);const valid=before&&after&&epoch(e.date)-epoch(before[0])<=7*86400000&&epoch(after[0])-epoch(e.date)<=7*86400000;append(eventDetail,node('p',meta[id][0]+': '+(valid?before[0]+' '+fmt(before[1])+' -> '+after[0]+' '+fmt(after[1])+' / 差 '+fmt(after[1]-before[1])+' '+(id==='ust10'?'pt':meta[id][1]):'比較に必要な前後データが未収録'),'small'));}
 append(eventDetail,node('p','統計対象月と発表日は別です。前日と当日以降の最初の日次値を比較（7日以内）。発表直後の反応や因果効果の推定ではありません。','small'),button('イベント選択を解除',()=>{Q.event=null;render();}));}
function chart(s,o,rows){const cv=o.canvas,w=Math.max(230,cv.parentElement.clientWidth-40),h=225,ratio=Math.min(devicePixelRatio||1,2);cv.width=w*ratio;cv.height=h*ratio;cv.style.height=h+'px';const c=cv.getContext('2d');c.scale(ratio,ratio);const [start,end]=windowDates();let lo=Math.min(...rows.map(r=>r[1])),hi=Math.max(...rows.map(r=>r[1]));const pad=(hi-lo||1)*.13;lo-=pad;hi+=pad;const x=t=>52+(t-start)/(end-start)*(w-70),y=v=>180-(v-lo)/(hi-lo)*150;c.font='11px sans-serif';c.fillStyle='#bcd0e0';c.strokeStyle='#2e465e';for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3,yy=y(v);c.beginPath();c.moveTo(51,yy);c.lineTo(w-12,yy);c.stroke();c.fillText(fmt(v,1),2,yy+4);}for(let i=0;i<3;i++){const t=start+(end-start)*i/2;c.fillText(new Date(t).toISOString().slice(0,7),Math.min(w-65,x(t)),206);}
 c.strokeStyle='#69dec8';c.lineWidth=1.7;c.beginPath();let prior=null;for(const r of rows){const t=epoch(r[0]);if(prior===null||t-prior>(meta[s.id][2].startsWith('月')?40:4)*86400000)c.moveTo(x(t),y(r[1]));else c.lineTo(x(t),y(r[1]));prior=t;}c.stroke();if(rows.length===1){c.beginPath();c.arc(x(epoch(rows[0][0])),y(rows[0][1]),3,0,7);c.fill();}
 if(Q.event){const xx=x(epoch(Q.event.date));c.strokeStyle='#f4c97c';c.setLineDash([5,4]);c.beginPath();c.moveTo(xx,20);c.lineTo(xx,185);c.stroke();c.setLineDash([]);c.fillStyle='#f4c97c';c.fillText('発表日',Math.min(w-55,Math.max(52,xx+4)),15);}c.fillStyle='#bcd0e0';c.fillText(unit(s),52,15);}
function render(){const [a,b]=windowDates();selected.textContent=new Date(a).toISOString().slice(0,10)+' - '+new Date(b).toISOString().slice(0,10)+' / 最終取得試行 '+D.attempted_at;controls.querySelectorAll('[data-macro-years]').forEach(e=>e.setAttribute('aria-pressed',String(!Q.event&&+e.dataset.macroYears===Q.years)));controls.querySelectorAll('[data-macro-mode]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.macroMode===Q.mode)));selector.querySelectorAll('button').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.macroSeries===Q.series)));eventInfo();
 for(const s of D.series){const o=cards.get(s.id);o.card.hidden=Q.series!=='all'&&Q.series!==s.id;if(o.card.hidden)continue;const all=values(s),rows=all.filter(r=>epoch(r[0])>=a&&epoch(r[0])<=b);o.rows=rows;o.cursor=Math.max(0,rows.length-1);o.canvas.hidden=!rows.length;o.details.hidden=!rows.length;o.status.textContent=s.status==='rights_pending'?'再掲載条件確認待ち':s.status==='retained'?'取得失敗 / 前回値保持':s.status==='available'?'一次データ収録':'未収録';const last=s.observations.at(-1);if(last&&Date.now()-epoch(last[0])>(['cpi','pce','unemployment'].includes(s.id)?95:15)*86400000)o.status.textContent+=' / 観測日が古い';o.status.className='p-badge '+(s.status==='available'?'':'p-warn');o.value.textContent=rows.length?fmt(rows.at(-1)[1])+' '+unit(s):'—';
 o.summary.textContent=s.id==='vix'?'系列の受け口は実装済み。公開サイトへの再配布許可を確認するまで数値は掲載しません。':meta[s.id][2]+' / 全履歴 '+s.observations.length+'点 / 表示 '+rows.length+'点 / 取得 '+(s.fetched_at||'—');o.readout.textContent=rows.length?rows.at(-1)[0]+' | '+fmt(rows.at(-1)[1])+' '+unit(s):'表示範囲のデータなし';
 o.table.replaceChildren();const head=node('tr');append(head,node('th','観測日 / 対象月'),node('th',unit(s)));o.table.append(append(node('thead'),head));const body=node('tbody');for(const r of rows.slice(-24))body.append(append(node('tr'),node('td',r[0]),node('td',fmt(r[1],3))));o.table.append(body);if(rows.length&&!M.hidden)chart(s,o,rows);}
}
$('tab-macro').addEventListener('click',()=>requestAnimationFrame(render));window.addEventListener('resize',()=>{if(!M.hidden)requestAnimationFrame(render);});
const entry=node('article',undefined,'p-card');append(entry,node('h3','マクロ時系列と連動'),node('p','経済カレンダーはBLS・BEA・Federal Reserveの公式日程を定期確認し、年間完全性ゲートを通過した日程だけ翌年へ拡張します。','small'),button('連動カレンダーを開く',()=>{activate($('tab-macro'));render();health.scrollIntoView({block:'start'});}));$('events').prepend(entry);
const coverage=node('article',undefined,'p-card');append(coverage,node('h3','v0.6.0 / 実装と残課題'),node('p','マクロ6系列の長期履歴、期間切替、経済カレンダー連動、年別Source Healthを実装。VIXの再掲載、株価の長期データ、予想値、実機Safari確認は残件。'));$('operations').prepend(coverage);
const age=$('age');if(age)age.textContent='株価・指数: 2026-09-10固定 / マクロ: 各系列の観測日 / カレンダー: Source Healthを確認';
Object.defineProperty(window,'EconomicsMacro',{value:Object.freeze({version:'0.6.0',seriesCount:7,availableCount:D.series.filter(s=>s.observations.length).length,eventsCount:K.events.length,yoy:rows=>yoy(rows),state:()=>Object.freeze({years:Q.years,series:Q.series,event:Q.event?.id||null})})});renderHealth();renderCalendar();render();
})();
